
echo [1/4] Activating virtual environment...
call backend\venv\Scripts\activate

echo [2/4] Starting Flask API in a new terminal...
start "Flask Server" cmd /k "backend\venv\Scripts\activate && python backend\main.py"
